name: teste

on:
  push:
    branch:
      - 'main'

jobs:
  build:
    runs-os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/steup-node@v1
        with:
          node-version: 16
      - run: npm c
      - run: npm run test
